# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install -r requirements.txt"
  - "pip install ."

script:
# Run the unit tests for GFFUtils
  - "python setup.py test"
# Run the example scripts
  - "cd examples/"
  - ./run_examples.sh

